baseURL = "/"
languageCode = "en-us"
title = "Game Cinematography Society"
theme = "gcs-theme"

# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "/about"
weight = 3

[[menu.main]]
name = "Articles"
URL = "/articles"
weight = 2

[[menu.main]]
name = "Contact"
URL = "/contact"
weight = 4

# only desktop menu
[[menu.desktop]]
name = "Articles"
URL = "/articles"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "Game Cinematography Society"
author = "Ryan Jones"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "A group for pushing cinematography within the game industry."
image = "#"

# blog
[params.blog]
heading = "Interested in knowing more? Find out who we are <a href=\"about\">here</a>."

# call to action
[params.call_to_action]
enable = false
title = "Contact us for more information."
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About the GCS"
content = "Find out more <a href=\"../about\">here</a>"
copyright = "Copyright &copy; 2021 Game Cinematographer Society"


############################# social site ########################
[params.social]
facebook = "#"
twitter = "#"
instagram = "#"
email = "ryan@gcsoc.org"
linkedin = "#"